### ISSUE TITLE
Calling for MDC-Web React developers

### ISSUE THREAD

**Issue by rustemgareev** [webdenim/awesome-material-components#1]
Hello,

@kradio3, @Hardtack, @jamesmfriedman, @miguel-orange, @gutenye.

I created this issue to connect developers of MDC-Web integrations for React in one place.

Awesome Material Components mentions [5 integrations of MDC-Web for React](https://github.com/webdenim/awesome-material-components#mdc-web-framework-integrations),
but real number of such projects is higher.

These works are good and I understand why developers want to create their own versions of MDC-Web for React. But I don't want developers to spread the efforts across multiple libraries with similar purpose.
Maybe you will have one source for incorporating MDC-Web for React? That will be useful for anyone.

If you know another developers working on React MDC-Web integrations and want them to join the discussion, please mention them here.

**Comment by hardtack** [comment]
@rustemgareev 

Hi, I created [react-material-components-web](https://github.com/react-mdc/react-material-components-web) just because there was no react wrapper for MDC in that time.
And it was made to be used in my company's side-project, the administration page.  But now, the side-project is postponed, so react-mdc project was postponed also.

Since I'm doing it individually, management of the project is strictly up to my personal schedule. I don't want to this project be unmanaged. So co-operation is what I always wanted.

But, incorporation would be very hard. For instance, my project, react-material-components-web, is highly bound to TypeScript. But most of other projects are not.
Since I don't prefer the untyped languages, I don't want to integrate it to plain javascript.

MDC-Web is managed by Google, but we are not. Incoporation without a design that all members agree with would be inefficient than single-maintainer project.

**Comment by rustemgareev** [comment]
@Hardtack, I added the description to react-material-components-web.

Will wait for responses from other authors.

**Comment by jamesmfriedman** [comment]
Hi, thanks for including me on this! I made RMWC because I couldn't find a complete integration somewhere else, here was my reasoning.

- @kradio3 had the full component surface mapped out, but didn't use the foundation classes, so it wasn't a full wrapper that was going to suit my needs.
- as @Hardtack already said, he used Typescript which is great, but didn't suit my needs. I actually looked through his code and embraced one of his principals which was making every MDC Dom Node it's own component so it can be recomposed with or without functionality.
- I never saw @miguel-orange version, but it looks like he's off to a good start
- I never saw @gutenye version, but it also looks like he's made some good progress.

Why I built my own:
- I had an immediate need and couldn't wait for it to be filled. I tried Material-UI, React-toolbox, and several others and kept getting bit in the ass
- I loved that Google is the one supporting their own design implementation, that way I can guarantee it was unopinionated
- I wanted to use Flow because it is optional and hidden from the end user, and also widely used in the React community
I wanted the ability to compose new components out of pieces of the material library. For instance, I've made a range slider that uses the same styles as MDC (and components) but has its own controller and two handles.

I currently have support from my company Bigsquid to continue working on this and it's being integrated into our own internal component library. I also have several personal projects built on it and the beginnings of some community support. I have a pipe dream of supporting React Native as well, but thats too much of a lift at the moment.

I would love to pool our efforts. My next big push is to get some polished docs up there. Thats the only thing holding me back from declaring an official V1 at the moment.

**Comment by rustemgareev** [comment]
> Incoporation without a design that all members agree with would be inefficient than single-maintainer project.

I think it's worth spend some time in a group discussing the design than reinvent the wheel alone, and get the abandoned project afterwards (not a personal attack, just my thoughts).

By the way, can you enable Gitter channels for your projects? I'm considering to add quick links to AMC items where possible.

**Comment by rustemgareev** [comment]
Closed as an official [MDC React](https://github.com/material-components/material-components-web-react) wrapper gets more traction.
